--POPOLAZIONE DB

--Popolamento Profili
CALL CREA_PROFILO('Genny03cry', 'Database03', 'Gennaro', 'De Luca', 'M', TO_DATE('04-11-2003', 'DD-MM-YYYY'));
CALL CREA_PROFILO('Gabbo', 'SonoIo02', 'Gabriele', 'Cifuni', 'F', TO_DATE('21-4-2002', 'DD-MM-YYYY'));
CALL CREA_PROFILO('DarkNine', 'Pagl1accio', 'Simone', 'Francesco', 'F', TO_DATE('21-11-2003', 'DD-MM-YYYY'));
CALL CREA_PROFILO('errore31', 'Sbagliato03', 'Antonio', 'Caruso', 'M', TO_DATE('27-05-2003', 'DD-MM-YYYY'));
CALL CREA_PROFILO('sunshine88', 'Sun@Sh1ne88$', 'Giovanni', 'Rossi', 'M', TO_DATE('01-01-1990', 'DD-MM-YYYY'));
CALL CREA_PROFILO('moonlight99', 'Moon!L1ght99%', 'Maria', 'Bianchi', 'F', TO_DATE('15-02-1988', 'DD-MM-YYYY'));
CALL CREA_PROFILO('starfire77', 'St4r#F1re77N', 'Luca', 'Verdi', 'M', TO_DATE('20-03-1992', 'DD-MM-YYYY'));
CALL CREA_PROFILO('oceanblue55', 'Oc3an*Blue55^', 'Anna', 'Neri', 'F', TO_DATE('25-04-1991', 'DD-MM-YYYY'));
CALL CREA_PROFILO('mountainpeak33', 'Mount@1nPe4k33!', 'Francesco', 'Martini', 'M', TO_DATE('30-05-1985', 'DD-MM-YYYY'));
CALL CREA_PROFILO('forestgreen22', 'F0rest#Green22$', 'Elisabetta', 'Ferrari', 'F', TO_DATE('10-06-1989', 'DD-MM-YYYY'));
CALL CREA_PROFILO('thunderstorm44', 'Thund3r@Storm44%', 'Matteo', 'Russo', 'M', TO_DATE('12-07-1987', 'DD-MM-YYYY'));
CALL CREA_PROFILO('rainbow87', 'R@inb0w87N', 'Laura', 'Romano', 'F', TO_DATE('18-08-1990', 'DD-MM-YYYY'));
CALL CREA_PROFILO('crystalwave66', 'Cryst@lW4ve66^', 'Giuseppe', 'Conti', 'M', TO_DATE('22-09-1993', 'DD-MM-YYYY'));
CALL CREA_PROFILO('whisperingwind88', 'Wh1sper!ngW1nd88$', 'Sara', 'Gallo', 'F', TO_DATE('15-10-1986', 'DD-MM-YYYY'));
CALL CREA_PROFILO('silvermoon11', 'S1lver@M00n11%', 'Andrea', 'Fontana', 'M', TO_DATE('23-11-1992', 'DD-MM-YYYY'));
CALL CREA_PROFILO('goldensun44', 'Gold@enS1n44N', 'Alessia', 'Moretti', 'F', TO_DATE('04-12-1988', 'DD-MM-YYYY'));
CALL CREA_PROFILO('stardust77', 'St@rD5ust77^', 'Davide', 'Esposito', 'M', TO_DATE('11-01-1991', 'DD-MM-YYYY'));
CALL CREA_PROFILO('morningdew33', 'M0rn!ngD3w33!', 'Martina', 'Ricci', 'F', TO_DATE('05-02-1989', 'DD-MM-YYYY'));
CALL CREA_PROFILO('twilightzone22', 'Twi1ight#Z0ne22$', 'Federico', 'Bruno', 'M', TO_DATE('13-03-1993', 'DD-MM-YYYY'));
CALL CREA_PROFILO('eveningsky99', 'Ev3n!ngSk9y99%', 'Valentina', 'Lombardi', 'F', TO_DATE('19-04-1990', 'DD-MM-YYYY'));
CALL CREA_PROFILO('northernlights88', 'North3rn#L1ghts88N', 'Simone', 'Bianco', 'M', TO_DATE('24-05-1987', 'DD-MM-YYYY'));
CALL CREA_PROFILO('serenityblue11', 'Seren!tyBl3u11^', 'Elena', 'Rizzo', 'F', TO_DATE('03-06-1994', 'DD-MM-YYYY'));
CALL CREA_PROFILO('whitelily44', 'Wh1teL1ly@44!', 'Riccardo', 'Marino', 'M', TO_DATE('07-07-1992', 'DD-MM-YYYY'));
CALL CREA_PROFILO('gentlebreeze77', 'Gent1e#Br33ze77$', 'Chiara', 'Santoro', 'F', TO_DATE('09-08-1988', 'DD-MM-YYYY'));
CALL CREA_PROFILO('darkshadow66', 'D@rkShad0w66%', 'Stefano', 'Grassi', 'M', TO_DATE('11-09-1991', 'DD-MM-YYYY'));
CALL CREA_PROFILO('brightstar33', 'Br1ght#St@r33N', 'Francesca', 'Pellegrini', 'F', TO_DATE('14-10-1993', 'DD-MM-YYYY'));
CALL CREA_PROFILO('wildflower88', 'W1ld!Fl0wer88^', 'Lorenzo', 'Fabbri', 'M', TO_DATE('21-11-1990', 'DD-MM-YYYY'));
CALL CREA_PROFILO('summerbreeze22', 'Summ3r@Br33ze22!', 'Giulia', 'Gatti', 'F', TO_DATE('25-12-1987', 'DD-MM-YYYY'));
CALL CREA_PROFILO('autumnglow99', 'Autumn#Gl0w99$', 'Nicola', 'Mancini', 'M', TO_DATE('30-01-1992', 'DD-MM-YYYY'));
CALL CREA_PROFILO('springblossom44', 'Spr!ngBl0ssom44%', 'Silvia', 'Leone', 'F', TO_DATE('28-02-1989', 'DD-MM-YYYY'));
CALL CREA_PROFILO('midnightmagic77', 'M1dN!ght#M@gic77N', 'Claudio', 'Longo', 'M', TO_DATE('14-03-1991', 'DD-MM-YYYY'));
CALL CREA_PROFILO('evergreen55', 'Ev3rg@r33n55^', 'Eleonora', 'Riva', 'F', TO_DATE('21-04-1994', 'DD-MM-YYYY'));
CALL CREA_PROFILO('lavenderdream11', 'Lav3nd3r@Dr3am11!', 'Alberto', 'Colombo', 'M', TO_DATE('15-05-1990', 'DD-MM-YYYY'));



--Popolamento Gruppi
CALL CREA_GRUPPO ('Fantacalcio', 'Ciao', 'Genny03cry');
CALL CREA_GRUPPO ('SSC_Napoli_Ultras', 'Solo fan del napoli', 'Genny03cry');
CALL CREA_GRUPPO ('Dungeons N Dragons', 'Gruppo pubblico di DND dove giocare e divertirsi', 'errore31');
CALL CREA_GRUPPO('Amanti del Cinema', 'Discussioni sui film e serie TV preferite', 'sunshine88');
CALL CREA_GRUPPO('Fotografia per Passione', 'Condividi le tue foto e apprendi nuove tecniche', 'moonlight99');
CALL CREA_GRUPPO('Viaggiatori del Mondo', 'Esperienze di viaggio e consigli di destinazioni', 'starfire77');
CALL CREA_GRUPPO('Cucinare con Amore', 'Ricette e trucchi per cucinare come uno chef', 'oceanblue55');
CALL CREA_GRUPPO('Appassionati di Tecnologia', 'Novità e discussioni su gadget e innovazioni', 'mountainpeak33');
CALL CREA_GRUPPO('Libri e Letteratura', 'Consigli di lettura e discussioni sui libri', 'forestgreen22');
CALL CREA_GRUPPO('Amici degli Animali', 'Tutto sui nostri amici a quattro zampe', 'thunderstorm44');
CALL CREA_GRUPPO('Fitness e Benessere', 'Consigli su esercizi, diete e stile di vita sano', 'rainbow87');
CALL CREA_GRUPPO('Musica per Tutti', 'Condivisione di playlist e nuovi artisti', 'crystalwave66');
CALL CREA_GRUPPO('Amanti dell''Arte', 'Discussioni e condivisioni su opere d''arte', 'whisperingwind88');
CALL CREA_GRUPPO('Gaming Club', 'Novità e recensioni su giochi e console', 'silvermoon11');
CALL CREA_GRUPPO('Moto e Avventure', 'Per gli appassionati di motociclette e avventure su due ruote', 'goldensun44');
CALL CREA_GRUPPO('Cinefili Anonimi', 'Proiezioni e recensioni di film', 'stardust77');
CALL CREA_GRUPPO('Bricolage e Fai-da-te', 'Progetti e consigli per il fai-da-te', 'morningdew33');
CALL CREA_GRUPPO('Amanti del Vino', 'Degustazioni e recensioni di vini', 'twilightzone22');
CALL CREA_GRUPPO('Cultura Giapponese', 'Scopri e condividi la cultura giapponese', 'eveningsky99');
CALL CREA_GRUPPO('Fotografia Naturalistica', 'Condivisione di foto di paesaggi e natura', 'northernlights88');
CALL CREA_GRUPPO('Club di Scrittura', 'Condividi i tuoi racconti e poesie', 'serenityblue11');
CALL CREA_GRUPPO('Film d''Animazione', 'Discussioni sui migliori film d''animazione', 'whitelily44');
CALL CREA_GRUPPO('Appassionati di Astronomia', 'Esplora l''universo con noi', 'gentlebreeze77');
CALL CREA_GRUPPO('Yoga e Meditazione', 'Consigli e sessioni di yoga e meditazione', 'darkshadow66');
CALL CREA_GRUPPO('Fotografia Urbane', 'Condivisione di foto e tecniche di fotografia urbana', 'brightstar33');
CALL CREA_GRUPPO('Giochi da Tavolo', 'Per gli amanti dei giochi da tavolo e di strategia', 'wildflower88');
CALL CREA_GRUPPO('Escursioni e Trekking', 'Organizziamo escursioni e trekking insieme', 'summerbreeze22');
CALL CREA_GRUPPO('Appassionati di Ciclismo', 'Condivisione di percorsi e consigli sul ciclismo', 'autumnglow99');
CALL CREA_GRUPPO('Club del Libro', 'Leggiamo e discutiamo un libro al mese', 'springblossom44');
CALL CREA_GRUPPO('Appassionati di Pesca', 'Consigli e condivisioni sulla pesca', 'midnightmagic77');
CALL CREA_GRUPPO('Viaggiatori in Camper', 'Esperienze e consigli di viaggio in camper', 'evergreen55');
CALL CREA_GRUPPO('Club della Risata', 'Condividi le tue barzellette e battute preferite', 'lavenderdream11');




--Popolamneto NOTIFICHE_RICHIESTE_ESITI
CALL CREA_RICHIESTA (1, 'Gabbo');
CALL CREA_RICHIESTA (1, 'DarkNine');
CALL CREA_RICHIESTA (1, 'errore31');
CALL CREA_RICHIESTA(3, 'sunshine88');
CALL CREA_RICHIESTA(6, 'moonlight99');
CALL CREA_RICHIESTA(7, 'starfire77');
CALL CREA_RICHIESTA(8, 'oceanblue55');
CALL CREA_RICHIESTA(9, 'mountainpeak33');
CALL CREA_RICHIESTA(10, 'forestgreen22');
CALL CREA_RICHIESTA(11, 'thunderstorm44');
CALL CREA_RICHIESTA(12, 'rainbow87');
CALL CREA_RICHIESTA(13, 'crystalwave66');
CALL CREA_RICHIESTA(14, 'whisperingwind88');
CALL CREA_RICHIESTA(15, 'silvermoon11');
CALL CREA_RICHIESTA(16, 'goldensun44');
CALL CREA_RICHIESTA(17, 'stardust77');
CALL CREA_RICHIESTA(18, 'morningdew33');
CALL CREA_RICHIESTA(19, 'twilightzone22');
CALL CREA_RICHIESTA(20, 'eveningsky99');
CALL CREA_RICHIESTA(21, 'northernlights88');
CALL CREA_RICHIESTA(22, 'serenityblue11');
CALL CREA_RICHIESTA(23, 'whitelily44');
CALL CREA_RICHIESTA(24, 'gentlebreeze77');
CALL CREA_RICHIESTA(25, 'darkshadow66');
CALL CREA_RICHIESTA(26, 'brightstar33');
CALL CREA_RICHIESTA(27, 'wildflower88');
CALL CREA_RICHIESTA(28, 'summerbreeze22');
CALL CREA_RICHIESTA(29, 'autumnglow99');
CALL CREA_RICHIESTA(30, 'springblossom44');
CALL CREA_RICHIESTA(31, 'midnightmagic77');
CALL CREA_RICHIESTA(32, 'evergreen55');
CALL CREA_RICHIESTA(4, 'moonlight99');
CALL CREA_RICHIESTA(5, 'starfire77');
CALL CREA_RICHIESTA(6, 'oceanblue55');
CALL CREA_RICHIESTA(7, 'mountainpeak33');
CALL CREA_RICHIESTA(8, 'forestgreen22');
CALL CREA_RICHIESTA(9, 'thunderstorm44');
CALL CREA_RICHIESTA(10, 'rainbow87');
CALL CREA_RICHIESTA(11, 'crystalwave66');
CALL CREA_RICHIESTA(12, 'whisperingwind88');
CALL CREA_RICHIESTA(13, 'silvermoon11');
CALL CREA_RICHIESTA(14, 'goldensun44');
CALL CREA_RICHIESTA(15, 'stardust77');
CALL CREA_RICHIESTA(16, 'morningdew33');
CALL CREA_RICHIESTA(17, 'twilightzone22');
CALL CREA_RICHIESTA(18, 'eveningsky99');
CALL CREA_RICHIESTA(19, 'northernlights88');
CALL CREA_RICHIESTA(20, 'serenityblue11');
CALL CREA_RICHIESTA(21, 'whitelily44');
CALL CREA_RICHIESTA(22, 'gentlebreeze77');
CALL CREA_RICHIESTA(23, 'darkshadow66');
CALL CREA_RICHIESTA(24, 'brightstar33');
CALL CREA_RICHIESTA(25, 'wildflower88');
CALL CREA_RICHIESTA(26, 'summerbreeze22');
CALL CREA_RICHIESTA(27, 'autumnglow99');
CALL CREA_RICHIESTA(28, 'springblossom44');
CALL CREA_RICHIESTA(29, 'midnightmagic77');
CALL CREA_RICHIESTA(30, 'evergreen55');
CALL CREA_RICHIESTA(31, 'lavenderdream11');
CALL CREA_RICHIESTA(4, 'errore31');

-- --Popolamneto NOTIFICHE_RICHIESTE_ESITI (ACCETTAZIONI)   
CALL ACCETTA_PROFILO('Gabbo', 1);
CALL ACCETTA_PROFILO('DarkNine', 1);
CALL RIFIUTA_PROFILO('moonlight99', 4);
CALL ACCETTA_PROFILO('starfire77', 5);
CALL ACCETTA_PROFILO('oceanblue55', 6);
CALL RIFIUTA_PROFILO('mountainpeak33', 7);
CALL ACCETTA_PROFILO('forestgreen22', 8);
CALL ACCETTA_PROFILO('thunderstorm44', 9);
CALL RIFIUTA_PROFILO('rainbow87', 10);
CALL ACCETTA_PROFILO('crystalwave66', 11);
CALL ACCETTA_PROFILO('whisperingwind88', 12);
CALL ACCETTA_PROFILO('goldensun44', 14);
CALL ACCETTA_PROFILO('stardust77', 15);
CALL RIFIUTA_PROFILO('morningdew33', 16);
CALL ACCETTA_PROFILO('twilightzone22', 17);
CALL ACCETTA_PROFILO('eveningsky99', 18);
CALL RIFIUTA_PROFILO('northernlights88', 19);
CALL ACCETTA_PROFILO('serenityblue11', 20);
CALL ACCETTA_PROFILO('whitelily44', 21);
CALL ACCETTA_PROFILO('darkshadow66', 23);
CALL ACCETTA_PROFILO('brightstar33', 24);
CALL RIFIUTA_PROFILO('wildflower88', 25);
CALL ACCETTA_PROFILO('summerbreeze22', 26);
CALL ACCETTA_PROFILO('autumnglow99', 27);
CALL RIFIUTA_PROFILO('springblossom44', 28);
CALL ACCETTA_PROFILO('midnightmagic77', 29);
CALL ACCETTA_PROFILO('evergreen55', 30);
CALL RIFIUTA_PROFILO('lavenderdream11', 31);
CALL RIFIUTA_PROFILO('moonlight99', 6);
CALL ACCETTA_PROFILO('starfire77', 7);
CALL ACCETTA_PROFILO('oceanblue55', 8);
CALL RIFIUTA_PROFILO('mountainpeak33', 9);
CALL ACCETTA_PROFILO('forestgreen22', 10);
CALL ACCETTA_PROFILO('thunderstorm44', 11);
CALL RIFIUTA_PROFILO('rainbow87', 12);
CALL ACCETTA_PROFILO('whisperingwind88', 14);
CALL RIFIUTA_PROFILO('silvermoon11', 15);
CALL ACCETTA_PROFILO('goldensun44', 16);
CALL ACCETTA_PROFILO('stardust77', 17);
CALL RIFIUTA_PROFILO('morningdew33', 18);
CALL ACCETTA_PROFILO('twilightzone22', 19);
CALL ACCETTA_PROFILO('eveningsky99', 20);
CALL RIFIUTA_PROFILO('northernlights88', 21);
CALL ACCETTA_PROFILO('whitelily44', 23);
CALL RIFIUTA_PROFILO('gentlebreeze77', 24);
CALL ACCETTA_PROFILO('darkshadow66', 25);
CALL ACCETTA_PROFILO('brightstar33', 26);
CALL RIFIUTA_PROFILO('wildflower88', 27);
CALL ACCETTA_PROFILO('summerbreeze22', 28);
CALL ACCETTA_PROFILO('autumnglow99', 29);
CALL RIFIUTA_PROFILO('springblossom44', 30);
CALL ACCETTA_PROFILO('midnightmagic77', 31);
CALL ACCETTA_PROFILO('evergreen55', 32);
CALL ACCETTA_PROFILO('errore31', 4);

--Popolamento Contenuti
CALL CREA_CONTENUTO(NULL,'Pako ha vinto il Fanta!!1!1!',1,'Gabbo');
CALL CREA_CONTENUTO(NULL, 'Thuram è troppo forte',1,'DarkNine');
CALL CREA_CONTENUTO(NULL, 'Buongiorno è troppo forte',1,'DarkNine');

CALL CREA_CONTENUTO(NULL, 'Discussione sul Signore Oscuro in DND', 3, 'sunshine88');
CALL CREA_CONTENUTO(NULL, 'Recensione di un film recente', 5, 'starfire77');
CALL CREA_CONTENUTO(NULL, 'Foto di un tramonto spettacolare', 6, 'oceanblue55');
CALL CREA_CONTENUTO(NULL, 'Consigli per un viaggio in Giappone', 8, 'forestgreen22');
CALL CREA_CONTENUTO(NULL, 'Ricetta per una cena romantica', 9, 'thunderstorm44');
CALL CREA_CONTENUTO(NULL, 'Ultime novità tecnologiche', 11, 'crystalwave66');
CALL CREA_CONTENUTO(NULL, 'Recensione di un libro di fantascienza', 12, 'whisperingwind88');
CALL CREA_CONTENUTO(NULL, 'Foto del mio cane in montagna', 14, 'goldensun44');
CALL CREA_CONTENUTO(NULL, 'Scheda di allenamento settimanale', 15, 'stardust77');
CALL CREA_CONTENUTO(NULL, 'Playlist di musica classica', 17, 'twilightzone22');
CALL CREA_CONTENUTO(NULL, 'Quadro di un artista locale', 18, 'eveningsky99');
CALL CREA_CONTENUTO(NULL, 'Recensione di un videogioco', 20, 'serenityblue11');
CALL CREA_CONTENUTO(NULL, 'Itinerario per un viaggio in moto', 21, 'whitelily44');
CALL CREA_CONTENUTO(NULL, 'Progetto di bricolage fai-da-te', 23, 'darkshadow66');
CALL CREA_CONTENUTO(NULL, 'Degustazione di vini italiani', 25, 'wildflower88');
CALL CREA_CONTENUTO(NULL, 'Fotografie di paesaggi naturali', 26, 'summerbreeze22');
CALL CREA_CONTENUTO(NULL, 'Poesia ispirata alla primavera', 28, 'springblossom44');
CALL CREA_CONTENUTO(NULL, 'Recensione di un film d''animazione', 29, 'midnightmagic77');
CALL CREA_CONTENUTO(NULL, 'Tecniche di meditazione avanzata', 31, 'lavenderdream11');
CALL CREA_CONTENUTO(NULL, 'Fotografia di architettura urbana', 32, 'errore31');
CALL CREA_CONTENUTO(NULL, 'Analisi critica di un vecchio film', 5, 'sunshine88');
CALL CREA_CONTENUTO(NULL, 'Ricordi di un viaggio indimenticabile', 7, 'starfire77');
CALL CREA_CONTENUTO(NULL, 'Trucchi per la fotografia', 8, 'oceanblue55');
CALL CREA_CONTENUTO(NULL, 'Guida alla cucina vegetariana', 10, 'forestgreen22');
CALL CREA_CONTENUTO(NULL, 'Recensione di un nuovo gadget', 11, 'thunderstorm44');
CALL CREA_CONTENUTO(NULL, 'Discussione su un libro di narrativa', 13, 'crystalwave66');
CALL CREA_CONTENUTO(NULL, 'Foto del mio gatto al parco', 14, 'whisperingwind88');
CALL CREA_CONTENUTO(NULL, 'Programma di allenamento per principianti', 16, 'goldensun44');
CALL CREA_CONTENUTO(NULL, 'Playlist di musica rock', 17, 'stardust77');
CALL CREA_CONTENUTO(NULL, 'Disegno di un paesaggio', 19, 'twilightzone22');
CALL CREA_CONTENUTO(NULL, 'Recensione di un gioco di ruolo', 20, 'eveningsky99');
CALL CREA_CONTENUTO(NULL, 'Itinerario per un viaggio in camper', 22, 'serenityblue11');
CALL CREA_CONTENUTO(NULL, 'Progetto di giardinaggio', 23, 'whitelily44');
CALL CREA_CONTENUTO(NULL, 'Recensione di un vino francese', 25, 'darkshadow66');
CALL CREA_CONTENUTO(NULL, 'Escursione nel parco nazionale', 27, 'wildflower88');
CALL CREA_CONTENUTO(NULL, 'Ricetta per un dolce estivo', 28, 'summerbreeze22');
CALL CREA_CONTENUTO(NULL, 'Recensione di un libro di avventura', 29, 'autumnglow99');
CALL CREA_CONTENUTO(NULL, 'Fotografie di animali selvatici', 31, 'midnightmagic77');
CALL CREA_CONTENUTO(NULL, 'Disegni a tema urbano', 32, 'evergreen55');
CALL CREA_CONTENUTO(NULL, 'Discussione su un nuovo film', 4, 'errore31');

--Popolamento Like
CALL CREA_LIKE ('DarkNine', 2);
CALL CREA_LIKE ('Gabbo', 2);
CALL CREA_LIKE ('DarkNine', 1);
CALL CREA_LIKE ('Gabbo', 1); 
CALL CREA_LIKE ('Gabbo', 4); 
CALL CREA_LIKE('sunshine88', 5);
CALL CREA_LIKE('starfire77', 24);
CALL CREA_LIKE('oceanblue55', 7);
CALL CREA_LIKE('forestgreen22', 26);
CALL CREA_LIKE('thunderstorm44', 9);
CALL CREA_LIKE('crystalwave66', 28);
CALL CREA_LIKE('whisperingwind88', 11);
CALL CREA_LIKE('goldensun44', 30);
CALL CREA_LIKE('stardust77', 13);
CALL CREA_LIKE('twilightzone22', 32);
CALL CREA_LIKE('eveningsky99', 15);
CALL CREA_LIKE('serenityblue11', 34);
CALL CREA_LIKE('whitelily44', 17);
CALL CREA_LIKE('darkshadow66', 18);
CALL CREA_LIKE('brightstar33', 19);
CALL CREA_LIKE('summerbreeze22', 20);
CALL CREA_LIKE('autumnglow99', 21);
CALL CREA_LIKE('midnightmagic77', 22);
CALL CREA_LIKE('evergreen55', 23);

--Popolamento Commenti
CALL CREA_COMMENTO('Non è vero che è troppo forte!!',2,'Gabbo'); 
CALL CREA_COMMENTO('Invece si, ha rovinato il gioco!!',2,'errore31'); 
CALL CREA_COMMENTO('🔥🔥🔥',2,'DarkNine'); 
CALL CREA_COMMENTO('Questo è un bellissimo post!', 5, 'sunshine88');
CALL CREA_COMMENTO('Mi piace molto questo contenuto!', 24, 'starfire77');
CALL CREA_COMMENTO('Post molto informativo, grazie per la condivisione!', 7, 'oceanblue55');
CALL CREA_COMMENTO('Ottimo post, ho imparato molto!', 26, 'forestgreen22');
CALL CREA_COMMENTO('Interessante, non vedo l''ora di leggere di più!', 9, 'thunderstorm44');
CALL CREA_COMMENTO('Questo post mi ha fatto riflettere, grazie!', 28, 'crystalwave66');
CALL CREA_COMMENTO('Mi è piaciuto molto leggere questo!', 11, 'whisperingwind88');
CALL CREA_COMMENTO('Post molto utile, grazie per averlo condiviso!', 30, 'goldensun44');
CALL CREA_COMMENTO('Ho trovato questo post molto interessante!', 13, 'stardust77');
CALL CREA_COMMENTO('Grazie per aver condiviso queste informazioni preziose!', 32, 'twilightzone22');
CALL CREA_COMMENTO('Ottimo lavoro, continua così!', 15, 'eveningsky99');
CALL CREA_COMMENTO('Mi è piaciuto molto il tuo post!', 34, 'serenityblue11');
CALL CREA_COMMENTO('Questo post è stato molto utile, grazie!', 17, 'whitelily44');
CALL CREA_COMMENTO('Ho trovato questo post molto utile!', 18, 'darkshadow66');
CALL CREA_COMMENTO('Grazie per aver condiviso queste informazioni!', 19, 'brightstar33');
CALL CREA_COMMENTO('Ottimo post, ho imparato molto!', 20, 'summerbreeze22');
CALL CREA_COMMENTO('Post molto informativo, grazie per la condivisione!', 21, 'autumnglow99');
CALL CREA_COMMENTO('Questo post mi ha fatto riflettere, grazie!', 22, 'midnightmagic77');
CALL CREA_COMMENTO('Mi è piaciuto molto leggere questo!', 23, 'evergreen55');





